name: 'Build and Deploy: Working Dev Server'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to ElephantServer droplet and rebuild
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{ secrets.DEPLOYER_HOST }}
                  username: ${{ secrets.DEPLOYER_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                    cd ElephantServer
                    git pull
                    docker-compose down
                    cd api
                    npm ci
                    cd ..
                    docker-compose up --build -d
                    echo ${{secrets.DEPLOYER_PASSWORD}} | sudo -S systemctl restart nginx -p ${{secrets.DEPLOYER_PASSWORD}}
